Project3/urls.py
from django.contrib import admin
from django.urls import path
from taskplanner import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #Auth 
    path('signup/', views.signupuser, name='signupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #Task planner
    path('', views.home, name='home'),
    path('add/', views.addtask, name='addtask'),
    path('task/<int:task_pk>', views.viewtask, name='viewtask'),
    path('task/<int:task_pk>/complete', views.completetask, name='completetask'),
    path('completed/', views.viewcompletedtasks, name='viewcompletedtasks'),
    path('task/<int:task_pk>/delete', views.deletetask, name='deletetask'),
    path('task/<int:task_pk>/redo', views.redotask, name='redotask'),


]

taskplanner/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.timezone import now
from django import forms

# Create your models here.

class Task(models.Model):
    # Title of the task:
    title = models.CharField(max_length=100)
    # Short description:
    description = models.TextField(blank=True)
    # When the task was created:
    created = models.DateField(auto_now_add=True)
    start_time = models.TimeField(null=True,blank=True)
    end_time = models.TimeField(null=True,blank=True)
    # The time you need to completed the task
    deadline = models.DateField(null=True,default=now()) 
    do_date = models.DateField(null=True,blank=True)
    # Task has been completed or not:
    completed = models.BooleanField(null=True,blank=True)
    # Date on which you completed the task:
    completed_date = models.DateTimeField(null=True,blank=True)
    
    # The user whom created the task:
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
# -----------Viewing the title in DjangoAdmin-------------
    def __str__(self):
        return self.title

taskplanner/forms.py
from django.forms import ModelForm
from django import forms
from .models import Task
class TaskForm(ModelForm):
    deadline = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    do_date = forms.DateField(widget=forms.TextInput(attrs={'type':'date'}))
    start_time = forms.TimeField(widget=forms.TextInput(attrs={'type':'time'}))
    end_time = forms.TimeField(widget=forms.TextInput(attrs={'type':'time'}))
    class Meta:
        model = Task
        fields = ['title','description','deadline','do_date','start_time','end_time']
    
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            data = {
                "class": "form-control"
            }
            self.fields[str(field)].widget.attrs.update(
                data
            )

taskplanner/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login,logout,authenticate
from .models import Task
from .forms import TaskForm
from django.utils import timezone
from django.contrib.auth.decorators import login_required

#-------------- Creating a user ------------------
def signupuser(request):

    if request.method == 'POST':
            if request.POST['password1'] == request.POST['password2']:
                try:
                    user = User.objects.get(username=request.POST['username'])
                    return render(request,'taskplanner/signupuser.html',{'error':'Username has already taken'})

                except User.DoesNotExist:
                    user = User.objects.create_user(request.POST['username'], password = request.POST['password1'])
                    login(request,user)
                    return redirect('home')
            else:
                return render(request,'taskplanner/signupuser.html',{'error':'Passwords must match!'})
    else:
        return render(request,'taskplanner/signupuser.html')
            

#-------------- Main Page: Contains the tasks ------------------
def home(request):
    try:
        tasks = Task.objects.filter(user = request.user, completed_date__isnull=True).order_by('deadline')
        return render(request, 'taskplanner/home.html', {'tasks':tasks})
    except TypeError:
        return render(request, 'taskplanner/home.html')
        
#-------------- Logging out a user ------------------
@login_required
def logoutuser(request):
    #Anything inside an url is a GET method
    # The urls loads automatically so if it is a GET method it will log them out
    if request.method == 'POST':
        logout(request)
        return redirect('home')

#-------------- Logging in a user ------------------
def loginuser(request):

    if request.method == 'POST':
            user = authenticate(username = request.POST['username'], password = request.POST['password'])
            print(request.POST['username'])
            if user is not None:
                login(request,user)
                return redirect('home')

            else:
                return render(request,'taskplanner/loginuser.html',{'error':"Your username or password is incorrect!"})
    else:
        return render(request, 'taskplanner/loginuser.html', {'form':AuthenticationForm()})

#-------------- Add a task ------------------
@login_required
def addtask(request):
    if request.method == 'GET':
        return render(request, 'taskplanner/addtask.html', {'form': TaskForm()})
    else:
        try:
            #----------Task created--------------
            form = TaskForm(request.POST)
            newtask = form.save(commit=False) # To not save in database immediately
            #Appending the task to the specific user 
            newtask.user = request.user
            newtask.save()
            return redirect('home')
        except ValueError:
            return render(request, 'taskplanner/addtask.html', {'form': TaskForm(),'error':'Improper data, try again!'})

#-------------- View a task separately -----------
@login_required
def viewtask(request, task_pk):
    task = get_object_or_404(Task,pk=task_pk, user = request.user)
    data = {'task':task,'form': TaskForm(task)}
    if request.method == 'GET':
        form = TaskForm(instance=task)
        data['form'] = form
        return render(request, 'taskplanner/task.html', data)
    else:
        try:
            #----------Task Modified--------------
            form = TaskForm(request.POST, instance=task)
            form.save()
            return redirect('home')
        except ValueError:
            data['error'] = 'Improper data, try again!'
            data['form'] = form
            return render(request, 'taskplanner/task.html',data)

#----------------- Complete a task ------------------
@login_required
def completetask(request,task_pk):
    task = get_object_or_404(Task,pk=task_pk, user = request.user)
    data = {'task':task}
    if request.method == 'POST':
        task.completed = True
        task.completed_date = timezone.now()
        task.save()
        return redirect('home')

#--------------- View Completed Tasks ---------------
@login_required
def viewcompletedtasks(request):
    try:
        tasks = Task.objects.filter(user = request.user, completed_date__isnull=False).order_by('-completed_date')
        return render(request, 'taskplanner/completedtasks.html', {'tasks':tasks})
    except TypeError:
        return render(request, 'taskplanner/home.html')

#--------------- Delete a task ---------------
@login_required
def deletetask(request, task_pk):
    task = get_object_or_404(Task,pk=task_pk, user = request.user)
    data = {'task':task}
    if request.method == 'POST':
        task.delete()
        return redirect('home')

#----------------- Redo a task ------------------
@login_required
def redotask(request,task_pk):
    task = get_object_or_404(Task,pk=task_pk, user = request.user)
    data = {'task':task}
    if request.method == 'POST':
        task.completed = False
        task.completed_date = None
        task.save()
        return redirect('home')

taskplanner/templates/taskplanner/addtask.html
{% extends 'taskplanner/base.html'%}

{% block content %}
    <div class="task card">
        <h1 class="text-center"> Create Task </h1>
        <h2 class="text-center text-danger">{{ error }}</h2>
        <form action="" method="post" class="task">
            {% for field in form %}
            {% if field.label == 'Do date' %}
                <hr>
                <h3 class="text-center"> Allocate time for your tasks!</h3>
                <br>
                <div class="mb-3">
                    <label class="form-label">Date</label>
                    {{field}}</div>
            {% else %}
            <div class="mb-3">
                <label class="form-label">{{field.label}}</label>
                {{field}}</div>
            {% endif %}
                    
            {% endfor %}
            <!-- <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                <input type="text" name="title" maxlength="100" required="" id="id_title" class="form-control">  
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                <textarea name="description" cols="40" rows="10" id="id_description" class="form-control"></textarea>
            </div>
            <div class="mb-3">
                <label for="id_deadline" class="form-label">Deadline</label>
                <input type="date" name="deadline" id="id_deadline" class="form-control">
                <div class="form-text"> You can enter time in any format <br> E.g. 45 minutes, 2 hours </div>
            </div>
            <hr>
            <h4 class="text-center"> Allocate time for your task!</h4>
            <div class="mb-3">
                <label for="id_do_date" class="form-label">Date</label>
                <input type="date" name="do_date" id="id_do_date" class="form-control">
            </div>
            <div class="mb-3">
                <label for="id_start_time" class="form-label" >Start Time</label>
                <input type="time" name="start_time" id="id_start_time" class="form-control">
            </div>
            <div class="mb-3">
                <label for="id_end_time" class="form-label" >End Time</label>
                <input type="time" name="end_time" id="id_end_time" class="form-control">
            </div>
             -->
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-success"> Create Task</button>
        </form>
        
    </div>
{% endblock %}

taskplanner/templates/taskplanner/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="{% static 'taskplanner/styles.css' %}" rel="stylesheet">
    <script src="{% static 'taskplanner/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
    <link rel="icon" type="image/png"  href="{% static 'taskplanner/logo.png' %}">
    <title>Task Planner</title>
</head>
<body>
    
    <nav class="navbar navbar-expand-md">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="{% static 'taskplanner/logo.png'%}" alt="">
            <span >Task Planner </span>
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse text-center" id="navbarSupportedContent">
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'addtask' %}">Add Task</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page"  href="{% url 'home' %}" >Current Tasks</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page"  href="{% url 'viewcompletedtasks' %}" > Completed Tasks </a>
              </li>
              </form>
              {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page">{{ user.username }}</a>
                </li>
                <form action="{% url 'logoutuser' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-danger">Logout</button>
                </form>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'signupuser' %}">Signup</a>
                  </li>
                <li class="nav-item">
                      <a class="nav-link active" aria-current="page" href="{% url 'loginuser' %}">Login</a>
                  </li>
                {% endif %}
              </ul>
          </div>
        </div>
    </nav>
  
    <div class="content">
      {% block content %}
      {% endblock %}
      
    </div>

</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</html>

taskplanner/templates/taskplanner/completedtasks.html
{% extends 'taskplanner/base.html'%}
{% block content %}
<br>
    <h3>Completed Tasks</h3>
    {% if tasks.count == 0 %}
    <h5 class="text-center text-primary landing">
        You do not have any completed tasks.
        To check if you have any current task to do, go to Current Tasks and select any task you would like to complete as soon as possible!
        <br>
        <br>
        <button class="btn btn-primary">
        <a class="nav-link active" aria-current="page" href="{% url 'addtask' %}">New Task</a>
        </button>

        <button class="btn btn-primary">
        <a class="nav-link active" aria-current="page" href="{% url 'home' %}">View current tasks</a>
        </button>
    </h5>
{% endif %}

<div class="viewtoggle btn-group container-fluid" role="group" aria-label="Basic example">
    <button type="button" class="btn btn-info" id="loginform"> Individual view</button>
    <button type="button" class="btn btn-secondary" id="signupform"> Table view </button>
  </div>

<ul class="soloview tasks">
    {% for task in tasks %}
    <li><div class="card">
        <div class="card-header">{{task.title}}</div>
        <div class="card-body">
        {% if task.description %}
            {{task.description}}
        {% endif %}
        <a href="{% url 'viewtask' task.id %}" class="stretched-link"></a>
        </div>
        <div class="flexy">
            <span class="text-center card-body start_time">
                Start time: {{task.start_time}}
            </span>
            <span class="text-center card-body end_time">
                End time: {{task.end_time}}
            </span>
        </div>
        {% if task.deadline %}
        <div class="card-footer">
            Completed on: {{task.completed_date}}
        </div>
        {% endif %}
    </div></li>
    {% endfor %}
</ul>

<ul class="completed tableview tasks">
    <table class="text-center">
        <tr class="text-center">
        <th>Title</th>
        <th> Deadline</th>
        <th>Completed Date</th>
        </tr>
    {% for task in tasks %}
    <!-- Stretched-link can stretch outside the container so position-relative is required -->
    <tr class="position-relative">
        <th>{{task.title}}<a href="{% url 'viewtask' task.id %}" class="stretched-link"></a></th>
        <th>{{task.deadline}}</th>
        <th>{{task.completed_date}}</th>
    </tr>
    {% endfor %}
</table>
</ul>
{% endblock %}

taskplanner/templates/taskplanner/home.html
{% extends 'taskplanner/base.html'%}
{% block content %}
    {% if not user.is_authenticated %}
    <br>
    <div class="text-center landing">
        <h3>Welcome to Task Planner!</h3>
        <p>
            Here you can manage your tasks and keep track of what has been and what is remaining very easily!
            You can customise your tasks, delete them, and even redo them if it comes up again!
        </p>
        <div>
            <button class="btn btn-outline-primary"><a class="nav-link active" aria-current="page" href="{% url 'signupuser' %}">Sign up here!</a></button>
            <button class="btn btn-outline-primary"><a class="nav-link active" aria-current="page" href="{% url 'loginuser' %}">Login here!</a></button>
        </div>
    </div>
    {% else %}
    <br>
    <h3>Your Tasks</h3>

    {% if tasks.count == 0 %}
        <h5 class="text-center text-primary landing">
            You do not have any pending tasks. Nice Job!
            To redo a task, go to Completed Tasks and select any task you would like to redo!
            <br>
            <br>
            <button class="btn btn-primary">
            <a class="nav-link active" aria-current="page" href="{% url 'addtask' %}">New Task</a>
            </button>
 
            <button class="btn btn-primary">
            <a class="nav-link active" aria-current="page" href="{% url 'viewcompletedtasks' %}">View completed tasks</a>
            </button>
        </h5>
    {% endif %}
    
    <div class="viewtoggle btn-group container-fluid" role="group" aria-label="Basic example">
        <button type="button" class="btn btn-info" id="loginform"> Individual view</button>
        <button type="button" class="btn btn-secondary" id="signupform"> Table view </button>
      </div>   
    <ul class="soloview tasks">
        {% for task in tasks %}
        <li><div class="card">
            <div class="card-header">{{task.title}}</div>
            <div class="card-body">
            {% if task.description %}
                {{task.description}}
            {% endif %}
            <a href="{% url 'viewtask' task.id %}" class="stretched-link"></a>
            </div>
            <div class="flexy">
                <span class="text-center card-body start_time">
                    Start time: {{task.start_time}}
                </span>
                <span class="text-center card-body end_time">
                    End time: {{task.end_time}}
                </span>
            </div>
            {% if task.deadline %}
            <div class="card-footer">
                Deadline: {{task.deadline}}
            </div>
            {% endif %}
        </div></li>
        {% endfor %}
    </ul>
    <ul class="current tableview tasks">
        <table class="text-center">
            <tr class="text-center">
            <th>Title</th>
            <th>Date</th>
            <th>Start time</th>
            <th>End Time</th>
            <th> Deadline</th>
            </tr>
        {% for task in tasks %}
    <!-- Stretched-link can stretch outside the container so position-relative is required -->
        <tr class="position-relative">
            <th>{{task.title}}<a href="{% url 'viewtask' task.id %}" class="stretched-link"></a></th>
            <th>{{task.do_date}}</th>
            <th>{{task.start_time}}</th>
            <th>{{task.end_time}}</th>
            <th>{{task.deadline}}</th>
        </tr>
        {% endfor %}
    </table>
    </ul>
    {% endif %}
{% endblock %}

taskplanner/templates/taskplanner/loginuser.html
<!-- Import the base template -->
{% extends 'taskplanner/base.html'%}

{% block content %}
<div class="login card">
    <h1>Login </h1>
    <h2>{{ error }}</h2>
    <form action="" method="post">
        <!-- CSRF TOKEN is necessary -->
        <div class="mb-3">
            <label for="id_username" class="form-label">Username</label>
            <input type="text" class="form-control" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
        </div>
        
        <div class="mb-3">
            <label for="id_password1" class="form-label">Password</label>    
            <input type="password" name="password" autocomplete="new-password" required="" id="id_password1" class="form-control" aria-describedby="passwordHelpBlock">
        </div>
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Login </button>
    </form>
    <a class="text-center" aria-current="page" href="{% url 'signupuser' %}"> New User? Sign Up here!</a>
</div>
{% endblock %}

taskplanner/templates/taskplanner/signupuser.html
<!-- Import the base template -->
{% extends 'taskplanner/base.html'%}


{% block content %}
<div class="signup card">
    <h1>Sign Up Page</h1>
    <h2>{{ error }}</h2>
    <form action="" method="post">
        <!-- CSRF TOKEN is necessary -->
        <div class="mb-3">
            <label for="id_username" class="form-label">Username</label>
            <input type="text" class="form-control" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus="" required="" id="id_username">
            <div class="form-text">Make sure your username is unique.</div>
        </div>
        <div class="mb-3">
            <label for="id_password1" class="form-label">Password</label>    
            <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" class="form-control" aria-describedby="passwordHelpBlock">
            <div id="passwordHelpBlock" class="form-text"> Your password must be 8-20 characters long.</div>
        </div>
        <div class="mb-3">
            <label for="id_password2" class="form-label">Confirm Password </label>    
            <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" class="form-control" aria-describedby="passwordHelpBlock">
            <div id="passwordHelpBlock" class="form-text"> Type the password again for confirmation.</div>
        </div>
    {% csrf_token %}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
    <a class="text-center" aria-current="page" href="{% url 'loginuser' %}">Already a user? Login here!</a>
</div>
{% endblock %}

taskplanner/templates/taskplanner/task.html
{% extends 'taskplanner/base.html'%}
{% block content %}  

<h2 class="text-danger"> {{ error }}</h2>
    <div class="card task">
        <h3 class="text-center">Modify task</h3>
        <!-- Save your task -->
        <form action="" method="post" class="task">
            <!-- <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                <input type="text" name="title" maxlength="100" required="" id="id_title" class="form-control" value="{{ task.title }}">  
            </div>
            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                <textarea name="description" cols="40" rows="10" id="id_description" class="form-control" value="">{{ task.description }}</textarea>
            </div>
            <div class="mb-3">
                <label for="id_deadline" class="form-label">Deadline</label>
                <input type="date" name="deadline" id="id_deadline" class="form-control" value="{{ task.deadline.year }}-{{ task.deadline.month }}-1{{ task.deadline.day }}">
                <div class="form-text"> Pick the deadline of the task! </div>
            </div>
            <hr>
            <h4 class="text-center"> Allocate time for your task!</h4>
            <div class="mb-3">
                <label for="id_do_date" class="form-label">Date</label>
                <input type="date" name="do_date" id="id_do_date" class="form-control" value="{{ task.do_date }}">
            </div>
            <div class="mb-3">
                <label for="id_start_time" class="form-label" >Start Time</label>
                <input type="time" name="start_time" id="id_start_time" class="form-control" value="{{ task.start_time }}">
                {{ task.start_time }}
            </div>
            <div class="mb-3">
                <label for="id_end_time" class="form-label" >End Time</label>
                <input type="time" name="end_time" id="id_end_time" class="form-control" value="{{ task.end_time }}">
                {{ task.end_time }}
            </div> -->
            {% for field in form %}
                {% if field.label == 'Do date' %}
                    <hr>
                    <h3 class="text-center"> Allocate time for your tasks!</h3>
                    <br>
                    <div class="mb-3">
                        <label class="form-label">Date</label>
                        {{field}}</div>
                {% else %}
                <div class="mb-3">
                    <label class="form-label">{{field.label}}</label>
                    {{field}}</div>
                {% endif %}
            {% endfor %}
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-success"> Save Task</button>
        {% if task.completed is not True %}
        <button type="button" class="btn btn-outline-primary" onclick="$('#complete').click()">Complete Task</button>
        {% else %}
        <button type="button" class="btn btn-outline-primary" onclick="$('#complete').click()">Redo Task </button>
        {% endif %}
        <button type="button" class="btn btn-outline-danger" onclick="$('#delete').click()">Delete Task </button>
        </form>
        <div class="buttons">
            <!-- Complete the task -->
            {% if task.completed is not True %}
            <form style='display: none;' action="{% url 'completetask' task.id %}" method="post">
                {% csrf_token %}
                <button type="submit" id="complete"> Complete Task </button>
            </form>
            <!-- If user wants to use the task again -->
            {% else %}
            <form style='display: none;' action="{% url 'redotask' task.id %}" method="post">
                {% csrf_token %}
                <button type="submit" id="complete"> Redo Task </button>
            </form>
            {% endif %}
            
            <!-- Delete the task -->
            <form style='display: none;' action="{% url 'deletetask' task.id %}" method="post">
                {% csrf_token %}
                <button type="submit" id="delete"> Delete Task </button>
            </form>
        </div>
    </div>
<a href="{% url 'home' %}" class="btn btn-outline-primary"> Go back </a>
<br>
{% endblock %}